# This is a basic workflow to help you get started with Actions

name: Create issues from todos
on:
  push:
    branches: [ master ]


jobs:
  todos:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
      - name: Run a one-line script
        uses: dtinth/todo-actions@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
